Import .mat files into Python with:
```Python
scipy.io.loadmat('filename.mat')
```
Output: dictionary with variable names as keys, and variable values as values.

In [11]:
import scipy.io as io
import numpy as np
mat = io.loadmat('BWDb1.mat')
print(mat)

NotImplementedError: Please use HDF reader for matlab v7.3 files

Ignore keys with double underscores at the beginning and end like `__this__`. In the above case, there are 3 variables in test.mat, one is 'spikes' from `datarun.spikes`. The other 2 are matrices with random numbers generated by `randn` in MATLAB.

``` MATLAB
spikes = datarun.spikes;
matrix2 = randn(3, 3);
matrix3 = randn(3, 3, 3);
```


In [3]:
print('matrix2:', mat['matrix2'])
print('row 1 column 1 of matrix2:', mat['matrix2'][0,0])

matrix2: [[-0.19241851 -1.40226897 -0.17737516]
 [ 0.88861043 -1.42237593 -0.19605349]
 [-0.76484924  0.48819391  1.41931015]]
row 1 column 1 of matrix2: -0.192418510588


In [4]:
print('matrix3:', mat['matrix3'])
print('matrix3[0,0,0]:', mat['matrix3'][0,0,0])

matrix3: [[[ 0.32519054 -0.0300513  -0.00684933]
  [-1.71151642  1.09326567  0.37137881]
  [ 0.31920674  0.07735909 -1.0890643 ]]

 [[-0.75492832 -0.16487902  1.53263031]
  [-0.10224245  1.1092733  -0.2255844 ]
  [ 0.3128586  -1.21411704  0.03255746]]

 [[ 1.37029854  0.62770729 -0.76966591]
  [-0.24144704 -0.86365282  1.11735614]
  [-0.86487992 -1.11350074  0.55252702]]]
matrix3[0,0,0]: 0.325190539456


In [5]:
print('Spikes of the first cell: ', mat['spikes'][0,0])
print('1st spike of the first cell: ', mat['spikes'][0,0][0,0])

print('Spikes of the second cell: ', mat['spikes'][1,0])
print('2nd spike of the second cell: ', mat['spikes'][1,0][1,0])

print(type(mat['spikes']))


Spikes of the first cell:  [[  1.64900000e-01]
 [  1.76650000e-01]
 [  2.16400000e-01]
 ..., 
 [  9.64421650e+02]
 [  9.69059850e+02]
 [  9.71703300e+02]]
1st spike of the first cell:  0.1649
Spikes of the second cell:  [[  1.55950000e-01]
 [  4.45200000e-01]
 [  7.87750000e-01]
 ..., 
 [  9.79414850e+02]
 [  9.79432950e+02]
 [  9.79484200e+02]]
2nd spike of the second cell:  0.4452
<class 'numpy.ndarray'>


Once we get PSTHs, we can put PSTHs of all neurons into a 2-d matrix.

In [3]:
import scipy.io as io
import numpy as np
matdata = io.loadmat('BWDb1.mat')
print(mat)

NotImplementedError: Please use HDF reader for matlab v7.3 files

In [12]:
import h5py
arrays = {}
f = h5py.File('BWDb1.mat')
for k, v in f.items():
    arrays[k] = np.array(v)

Variables in .mat:  dict_keys(['Psth', 'PsthTime', 'mov'])


In [14]:
print('Variables in .mat: ', arrays.keys())
print('Size of movie: ', np.shape(arrays['mov']))

Variables in .mat:  dict_keys(['Psth', 'PsthTime', 'mov'])
Size of movie:  (215901, 53, 40)


In [15]:
print(arrays)

{'Psth': array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]]), 'PsthTime': array([[  4.39000000e-02],
       [  6.02835000e-02],
       [  7.66670000e-02],
       ..., 
       [  3.58340287e+03],
       [  3.58341946e+03],
       [  3.58343605e+03]]), 'mov': array([[[ 0.98000002,  0.02000001,  0.02000001, ...,  0.98000002,
          0.02000001,  0.02000001],
        [ 0.98000002,  0.98000002,  0.98000002, ...,  0.02000001,
          0.02000001,  0.02000001],
        [ 0.98000002,  0.02000001,  0.02000001, ...,  0.98000002,
          0.02000001,  0.98000002],
        ..., 
        [ 0.02000001,  0.02000001,  0.02000001, ...,  0.02000001,
          0.98000002,  0.02000001],
        [ 0.02000001,  0.98000002,  0.98000002, ...,  0.98000002,
          0.98000002,  0.980

In [21]:
dir(arrays)

['__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'clear',
 'copy',
 'fromkeys',
 'get',
 'items',
 'keys',
 'pop',
 'popitem',
 'setdefault',
 'update',
 'values']

In [22]:
dir()

['In',
 'Out',
 '_',
 '_18',
 '_21',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i10',
 '_i11',
 '_i12',
 '_i13',
 '_i14',
 '_i15',
 '_i16',
 '_i17',
 '_i18',
 '_i19',
 '_i2',
 '_i20',
 '_i21',
 '_i22',
 '_i3',
 '_i4',
 '_i5',
 '_i6',
 '_i7',
 '_i8',
 '_i9',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 '_sh',
 'arrays',
 'exit',
 'f',
 'get_ipython',
 'h5py',
 'io',
 'k',
 'np',
 'quit',
 'v']